/* Generated By:JavaCC: Do not edit this line. TALParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TALParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAR = 5;
  /** RegularExpression Id. */
  int RPAR = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int LBRACK = 10;
  /** RegularExpression Id. */
  int RBRACK = 11;
  /** RegularExpression Id. */
  int OR = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int EXISTS = 15;
  /** RegularExpression Id. */
  int FORALL = 16;
  /** RegularExpression Id. */
  int IMPLIC = 17;
  /** RegularExpression Id. */
  int EQUIV = 18;
  /** RegularExpression Id. */
  int IDENT = 19;
  /** RegularExpression Id. */
  int VAR = 20;
  /** RegularExpression Id. */
  int NUM = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"exists\"",
    "\"forall\"",
    "\"->\"",
    "\"<->\"",
    "<IDENT>",
    "<VAR>",
    "<NUM>",
  };

}
