/* Generated By:JavaCC: Do not edit this line. AlphabetParserConstants.java */
package parser.alphabet;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AlphabetParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LACC = 9;
  /** RegularExpression Id. */
  int RACC = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int SEMICOLON = 12;
  /** RegularExpression Id. */
  int FLUENTS = 13;
  /** RegularExpression Id. */
  int ACTIONS = 14;
  /** RegularExpression Id. */
  int CONSTANTS = 15;
  /** RegularExpression Id. */
  int IDENT = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"fluents\"",
    "\"actions\"",
    "\"constants\"",
    "<IDENT>",
  };

}
