//
// Generated by JTB 1.3.2
//

package parser.visitor;
import parser.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> fof()
    * f1 -> <EOF>
    */
   public void visit(one_line n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> implication()
    * f1 -> ( <EQUIV> implication() )*
    */
   public void visit(fof n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> disjunction()
    * f1 -> ( <IMPLIC> disjunction() )*
    */
   public void visit(implication n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> conjunction()
    * f1 -> ( <OR> conjunction() )*
    */
   public void visit(disjunction n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> unary()
    * f1 -> ( <AND> unary() )*
    */
   public void visit(conjunction n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> literal()
    *       | quantification()
    */
   public void visit(unary n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> ( <EXISTS> | <FORALL> )
    * f1 -> <VAR>
    * f2 -> <COLON>
    * f3 -> unary()
    */
   public void visit(quantification n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> atom()
    *       | negation()
    */
   public void visit(literal n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <NOT>
    * f1 -> unary()
    */
   public void visit(negation n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> terminal()
    *       | <LPAR> fof() <RPAR>
    *       | <LBRACK> fof() <RBRACK>
    */
   public void visit(atom n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <VAR>
    *       | predicate()
    */
   public void visit(terminal n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENT>
    * f1 -> [ argblock() ]
    */
   public void visit(predicate n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> <LPAR>
    * f1 -> [ args() ]
    * f2 -> <RPAR>
    */
   public void visit(argblock n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> arg()
    * f1 -> ( <COMMA> arg() )*
    */
   public void visit(args n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> predicate()
    *       | <IDENT>
    *       | <VAR>
    *       | <NUM>
    */
   public void visit(arg n) {
      n.f0.accept(this);
   }

}
