//
// Generated by JTB 1.3.2
//

package parser.visitor;
import parser.syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> fof()
    * f1 -> <EOF>
    */
   public R visit(one_line n, A argu);

   /**
    * f0 -> implication()
    * f1 -> ( <EQUIV> implication() )*
    */
   public R visit(fof n, A argu);

   /**
    * f0 -> disjunction()
    * f1 -> ( <IMPLIC> disjunction() )*
    */
   public R visit(implication n, A argu);

   /**
    * f0 -> conjunction()
    * f1 -> ( <OR> conjunction() )*
    */
   public R visit(disjunction n, A argu);

   /**
    * f0 -> unary()
    * f1 -> ( <AND> unary() )*
    */
   public R visit(conjunction n, A argu);

   /**
    * f0 -> literal()
    *       | quantification()
    */
   public R visit(unary n, A argu);

   /**
    * f0 -> ( <EXISTS> | <FORALL> )
    * f1 -> <VAR>
    * f2 -> <COLON>
    * f3 -> unary()
    */
   public R visit(quantification n, A argu);

   /**
    * f0 -> atom()
    *       | negation()
    */
   public R visit(literal n, A argu);

   /**
    * f0 -> <NOT>
    * f1 -> unary()
    */
   public R visit(negation n, A argu);

   /**
    * f0 -> terminal()
    *       | <LPAR> fof() <RPAR>
    *       | <LBRACK> fof() <RBRACK>
    */
   public R visit(atom n, A argu);

   /**
    * f0 -> <VAR>
    *       | predicate()
    */
   public R visit(terminal n, A argu);

   /**
    * f0 -> <IDENT>
    * f1 -> [ argblock() ]
    */
   public R visit(predicate n, A argu);

   /**
    * f0 -> <LPAR>
    * f1 -> [ args() ]
    * f2 -> <RPAR>
    */
   public R visit(argblock n, A argu);

   /**
    * f0 -> arg()
    * f1 -> ( <COMMA> arg() )*
    */
   public R visit(args n, A argu);

   /**
    * f0 -> predicate()
    *       | <IDENT>
    *       | <VAR>
    *       | <NUM>
    */
   public R visit(arg n, A argu);

}
