//
// Generated by JTB 1.3.2
//

package parser.visitor;
import parser.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJVoidDepthFirst<A> implements GJVoidVisitor<A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
      }
   }

   public void visit(NodeOptional n, A argu) {
      if ( n.present() )
         n.node.accept(this,argu);
   }

   public void visit(NodeSequence n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeToken n, A argu) {}

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> fof()
    * f1 -> <EOF>
    */
   public void visit(one_line n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> implication()
    * f1 -> ( <EQUIV> implication() )*
    */
   public void visit(fof n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> disjunction()
    * f1 -> ( <IMPLIC> disjunction() )*
    */
   public void visit(implication n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> conjunction()
    * f1 -> ( <OR> conjunction() )*
    */
   public void visit(disjunction n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> unary()
    * f1 -> ( <AND> unary() )*
    */
   public void visit(conjunction n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> literal()
    *       | quantification()
    */
   public void visit(unary n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> ( <EXISTS> | <FORALL> )
    * f1 -> <VAR>
    * f2 -> <COLON>
    * f3 -> unary()
    */
   public void visit(quantification n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
   }

   /**
    * f0 -> atom()
    *       | negation()
    */
   public void visit(literal n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <NOT>
    * f1 -> unary()
    */
   public void visit(negation n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> terminal()
    *       | <LPAR> fof() <RPAR>
    *       | <LBRACK> fof() <RBRACK>
    */
   public void visit(atom n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <VAR>
    *       | predicate()
    */
   public void visit(terminal n, A argu) {
      n.f0.accept(this, argu);
   }

   /**
    * f0 -> <IDENT>
    * f1 -> [ argblock() ]
    */
   public void visit(predicate n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> <LPAR>
    * f1 -> [ args() ]
    * f2 -> <RPAR>
    */
   public void visit(argblock n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
   }

   /**
    * f0 -> arg()
    * f1 -> ( <COMMA> arg() )*
    */
   public void visit(args n, A argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
   }

   /**
    * f0 -> predicate()
    *       | <IDENT>
    *       | <VAR>
    *       | <NUM>
    */
   public void visit(arg n, A argu) {
      n.f0.accept(this, argu);
   }

}
