//
// Generated by JTB 1.3.2
//

package parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> <NOT>
 * f1 -> unary()
 */
public class negation implements Node {
   public NodeToken f0;
   public unary f1;

   public negation(NodeToken n0, unary n1) {
      f0 = n0;
      f1 = n1;
   }

   public negation(unary n0) {
      f0 = new NodeToken("not");
      f1 = n0;
   }

   public void accept(parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

