//
// Generated by JTB 1.3.2
//

package parser.syntaxtree;

/**
 * Grammar production:
 * f0 -> fof()
 * f1 -> <EOF>
 */
public class one_line implements Node {
   public fof f0;
   public NodeToken f1;

   public one_line(fof n0, NodeToken n1) {
      f0 = n0;
      f1 = n1;
   }

   public one_line(fof n0) {
      f0 = n0;
      f1 = new NodeToken("");
   }

   public void accept(parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

